### ISSUE TITLE
Define symbolic name for the most up to date version of a component: "current" or "latest"

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/docs.asciidoctor.org#26]
_Context: Initiated as gitter conversation, we can use this issue as record. I personally don't like not being able to review desitions processes._

Goal: [paraphrasing @mojavelinux ] The idea is that you can bookmark the doc and it will be stable (always showing the most recent docs). [...] we definitely need to settle because we don't want to have to maintain redirects because we change it after we go live ;)

@djenks mentioned:
"Reading that sentence, it seems sort of clear that "latest" would be a better name for the "latest" version.
"current" and "most recent" are not obvious synonyms to me. "Latest" and "most recent" are pretty clear synonyms."

/cc @Mogztter

**Comment by abelsromero** [comment]
For me **"latest"**, sounds better and is the word that comes naturally to me when thinking about software releases.

Also according to the dictionary "current" refers to something in motion which does not match my idea of releases, witch to me are more like fixed snapshots.

**Comment by slonopotamus** [comment]
I want also suggest `stable`. `latest` feeld like "something from the HEAD commit of repository".

**Comment by mojavelinux** [comment]
Stable is always tempting, but quickly rendered meaningless when you realize that it could refer to any past stable release. And while it might be accurate to say that stable is meant to refer to the URL being stable, that would be way too confusing.

It's important to note that "latest" is very well defined in Antora. Latest is defined as the greatest non-prerelease. See https://docs.antora.org/antora/2.3/how-component-versions-are-sorted/#latest-version

Btw, I did do a poll about this. "latest" was the clear winner among those who responded (108 votes). See https://twitter.com/mojavelinux/status/1323543716796096514

**Comment by mojavelinux** [comment]
The slightly uphill battle we're facing is that many new sites are adopting "current". However, to me, that is a problematic term. Current to whom? It could be interpreted as the release the user is currently on, which is not necessarily the one that was just released.

There isn't a perfect term. But from my perspective, "latest" has been long used in tech to mean the latest stable release. And something that isn't stable is labeled as such, such as "unstable", "alpha", "beta", "next", "dev", or generally "prerelease".

**Comment by mojavelinux** [comment]
I should at least mention that it is possible to use no segment at all (e.g., `/asciidoctor/syntax-highlighting/`. However, doing so seems to leave me very nervous because it makes it harder to configure redirects if we ever have to change it.

**Comment by abelsromero** [comment]
Thanks @Mogztter for findind previous conversations:
* https://github.com/asciidoctor/asciidoctor.org/issues/977#issuecomment-721040165
* https://twitter.com/joschi83/status/1323545234651947008

Unless I am missing somehting, I think it's pretty much "latest" then.

**Comment by mojavelinux** [comment]
Thanks for the feedback!

**Comment by mojavelinux** [comment]
For the AsciiDoc docs component, we are going to continue to use the exact version name "current" (unrelated to this issue). That's because the language doesn't yet have versions, but we anticipate it will in the future. We're reserving space for it. When we say "current" in this context, we mean "how it is known currently". In essence, it's the odd one out of the bunch.

**Comment by mojavelinux** [comment]
resolved by PR #28
