### ISSUE TITLE
Set up CI for Netlify deploy preview

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/docs.asciidoctor.org#3]
Add the appropriate configuration files and profile information to enable PR previews of the documentation sites.
Also determine the transitional requirements to publish the docs sites and replace the current documentation pages, testing the redirects, setting up UI/supplemental UI files, and appending the docs to the pages still in the current project site. The long term goal being that the project site pages (non-docs) will eventually be migrated off of Awestruct.

**Comment by mojavelinux** [comment]
We'll also need to figure out what our strategy is for nightly / triggered builds. We might want to trigger builds based on activity from the individual repositories. The Travis build would ping a netlify webook, which would kick off a deploy from the master branch of the playbook repository.

**Comment by graphitefriction** [comment]
Closed by PR #4
