### ISSUE TITLE
Document [%collapsible] and [%autofit]

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/docs.asciidoctor.org#49]
I just wanted to double check [this issue](https://github.com/asciidoctor/asciidoctor.org/issues/943) isn't lost in the migration to the new asciidoc documentaion. Back in May 2020, @mojavelinux mentioned that the issue was transferred to this project, but I couldn't find it. Please feel free to close if I'm opening this in the wrong place. Thanks!

**Comment by mojavelinux** [comment]
Docs issues for the AsciiDoc language should now be reported at https://github.com/asciidoctor/asciidoc-docs. Can you please file the issue there? And since these are two separate features, can you file them as separate issues? They shouldn't be grouped just because they are both undocumented.
