### ISSUE TITLE
Site Indexer workflow can't work

### ISSUE THREAD

**Issue by KevinLoveGitHub** [asciidoctor/docs.asciidoctor.org#71]
In `indexer.xml` file, why replace `.xml` with `-home.xml`
 `SITEMAP_URL=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG')).sitemap_urls[0].replace('.xml', '-home.xml')")`

**Comment by mojavelinux** [comment]
Thanks for the heads up. We had renamed the component from home to ROOT, but I forgot to update this workflow script. It's trying to locate [this sitemap](https://docs.asciidoctor.org/sitemap-ROOT.xml) file, which contains the last updated date for the site. I just updated the workflow.
